services:
  mysql:
    image: mysql:8.0
    container_name: admin_db
    # Uncomment below when on Mac M1
    # platform: linux/arm64/v8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: admin_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - 3308:3306

  adminer:
    image: adminer
    container_name: admin_db_adminer
    restart: always
    ports:
      - 8088:8080
    environment:
      - ADMINER_DEFAULT_SERVER=admin_db